---
name: Run VM-MANAGER-PR-FLOW

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: "**"

jobs:
  TriggerWorkfows:
    uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
    with:
      EVENT: ${{ toJSON(github.event) }}
